# Generated by Django 3.2.9 on 2021-11-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_category_game_gamecategory_rating_review_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='estimated_time_to_play',
            field=models.CharField(max_length=60),
        ),
    ]
